### ISSUE TITLE
0.44 (as used in lombook 1.18.24) not tagged

### ISSUE THREAD

**Issue by mirabilos** [rzwitserloot/lombok.patcher#10]
The tag for the release is missing in git.

**Comment by mirabilos** [comment]
Looking at `src/patcher/lombok/patcher/Version.java` the source code for the release 0.44 is also not present in git `master`…

**Comment by Harmelodic** [comment]
Notifying: @rzwitserloot @rspilker @Rawi01 @mmoayyed 👋 ❤️ 

Indication seems to be that code is missing in the `master` branch that should be there, and there are tags missing.

How do merges and releases work here? What do we need to do to get `lombok.patcher` fixed up so we can start merging things in again?

I ask since this currently at the top of a chain of things that are blocking Lombok from supporting Java 19 😭

**Comment by alexanderankin** [comment]
@Harmelodic you can take the version that folks have compiled in projectlombok/lombok#3264 and publish to your private repo at work (i assume this is what "top of a chain of things that are block[ed]" means), or clone all these repos, check out the respective branches and build that locally and publish that.

**Comment by Harmelodic** [comment]
@alexanderankin
Could work for people as a temporary fix for people directly consuming Lombok, or for people happy with building versions and defining dependency overrides.

For my case, I _**really**_ don't want to run my own custom Lombok packages - I just want the open-source, provided ones to work and support latest & future versions of Java.

The other limiting factor for me is that I use [Spring Boot Dependencies](https://docs.spring.io/spring-boot/docs/current/reference/html/dependency-versions.html#:~:text=0.9.2.RELEASE-,org.projectlombok,-lombok) so that I don't have to manage lots of versions and have Spring handle dependency management.

Since Spring uses the official releases, it's in my interest to get this just fixed and released.

**Comment by Harmelodic** [comment]
Anyway, key question:

**_How do merges and releases work here? What do we (I) need to do to get `lombok.patcher` fixed up so we can start merging things in again?_**

**Comment by rzwitserloot** [comment]
`git push` not pushing tags tripped me up. Just pushed it.
